name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: тест
      id: ''
      uses: education/autograding-io-grader@v1
      with:
        test-name: тест
        setup-command: ''
        command: node index.js
        input: ''
        expected-output: "#"
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        _RESULTS: "${{steps..outputs.result}}"
      with:
        runners: ''
